var stuff, thing;

thing = new PersistentReactiveDict('thing', 'temporary');
stuff = new PersistentReactiveDict('stuff', 'temporary');

Tinytest.add("defaults persistent", function(test) {
  var foo;
  foo = new PersistentReactiveDict('foofoofoo1234124');
  return test.equal('persistent', foo.mode);
});

Tinytest.add("alternate mode", function(test) {
  var foo;
  foo = new PersistentReactiveDict('barbarbar1234124', 'authenticated');
  return test.equal('authenticated', foo.mode);
});

Tinytest.add("gets undefined", function(test) {
  var result;
  result = thing.get('something');
  test.equal(void 0, result);
  result = stuff.get('something');
  return test.equal(void 0, result);
});

Tinytest.add("sets & gets", function(test) {
  var result;
  result = thing.set('something', 'awesome');
  test.equal(void 0, result);
  result = thing.get('something');
  test.equal('awesome', result);
  result = stuff.set('something', 'amazing');
  test.equal(void 0, result);
  result = stuff.get('something');
  test.equal('amazing', result);
  result = thing.get('something');
  return test.equal('awesome', result);
});

Tinytest.add("clear", function(test) {
  var result;
  result = thing.set('different', 'awesome');
  test.equal(void 0, result);
  result = thing.get('different');
  test.equal('awesome', result);
  result = stuff.set('different', 'amazing');
  test.equal(void 0, result);
  result = stuff.get('different');
  test.equal('amazing', result);
  result = thing.get('something');
  test.equal('awesome', result);
  result = thing.clear('different');
  test.equal(void 0, result);
  result = thing.get('different');
  test.equal(void 0, result);
  result = stuff.get('different');
  return test.equal('amazing', result);
});

// ---
// generated by coffee-script 1.9.2
